version: 0.2

env:
  variables:
    AWS_REGION: ca-central-1
    ACCOUNT_ID: 042983202480
    IMAGE_NAME: bank-rest-api
    CONTAINER_NAME: bank-rest-api

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - mvn clean package -DskipTests
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - REPOSITORY_URI=042983202480.dkr.ecr.ca-central-1.amazonaws.com/bank-rest-api

  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
